### ISSUE TITLE
Test binaryen textual format

### ISSUE THREAD

**Issue by manuranga** [poorna2152/nballerina#1]
Let's consider following ballerina code (from [testSuite](https://github.com/ballerina-platform/nballerina/blob/main/compiler/testSuite/01-ifelse/2-v.bal)).
```ballerina
function printBoolean(boolean b) {
    if b {
        io:println(1);
    }
    else {
        io:println(0);
    }
}

```
It will get compiled to a bir structure similar to following (since we don't have an official textual format yet, this is just some pseudo-ir code). You may debug `nback:buildModule` if you need to see the exact structure.

```bir
printBoolean(boolean %b) returns () {
    boolean %b
    boolean %1
    boolean %2
    bb0 {
        INSN_COND_BRANCH operand: %b ifTrue: bb1 ifFalse: bb2
    }
    bb1 {
        INSN_CALL func:"io:println" args: [1]
        INSN_BRANCH bb3
    }
    bb2 {
        INSN_CALL func:"io:println" args: [0]
        INSN_BRANCH bb3
    }
    bb3 {
        INSN_RET operand: ()
    }
}
```
- [ ] Hand write equivalent function in binaryen textual format,  and show the code.
       Notes:
      - Don't use structured control flow, ie: wasm if-else.
      - You'll need to write the print runtime function (let's call `_Bb02ioprintln`), which may use JavaScript console log API. 

- [ ] Convert it to `wat` text format (and `wasm`) using tools provided by binaryen. Show the comand-line instructions you used.
- [ ] Verify it works correctly in a browser setting. Show any additional code (eg:HTML/JS) you had to use. Paste to GitHub Gist and link here.

**Comment by manuranga** [comment]
Unfortunately it doesn't look to me like it's going to work
```wat
(module
  (func (export "jump")
    (block
      (block $a
          (nop)
      )
      (block $b
          (br_if $a (i32.const 0)) ;; gives: [parse exception: use of popped label in sourceToUnique]Fatal: error in parsing input
          ;; With (br_if $c (i32.const 0)) it gives: [parse exception: bad label in sourceToUnique]Fatal: error in parsing input
          ;; With (br_if $b (i32.const 0)) it runs Ok
      )
      (block $c
          (nop)
      )
    )
))
```
I tested using `wasm-as` tool. Not sure if there is any other way I am missing.

**Comment by poorna2152** [comment]
https://github.com/poorna2152/nballerina/tree/binaryen-test/wasm-files

**Comment by manuranga** [comment]
Output looks good. But the C code to generate it should follow the above bir structure, not the output. (unless we are doing the relooping ourselves). Eg: when there is a `INSN_BRANCH` instruction in bir, relevant C code should have something like`RelooperAddBranch`.

**Comment by poorna2152** [comment]
Updated the branch with a new relooper.c file. The main.wat is corresponds to the output of the relooper.c. It uses the if control construct in the control flow.

**Comment by manuranga** [comment]
When I put your above output though wasm opt (`./wasm-opt -O3 poorna.wat --print`) I get following
```wat
(module
 (type $i32_=>_none (func (param i32)))
 (import "console" "log" (func $println (param i32)))
 (export "printBoolean" (func $printBoolean))
 (func $printBoolean (; has Stack IR ;) (param $0 i32)
  (call $println
   (if (result i32)
    (local.get $0)
    (i32.const 0)
    (i32.const 1)
   )
  )
 )
)
```
This is good news, looks like the heavy lifting is done by wasm opt, relooper is thin, so it is viable to replicate relooper in Ballerina.

**Comment by poorna2152** [comment]
In the Readme file under the [tools section](https://github.com/WebAssembly/binaryen#tools) none of the tools are specified to work with binaryen text format. Even the **wasm-as** is said to be working with the WebAssembly in text format (currently S-Expression format).

The [wasm-as](https://github.com/WebAssembly/binaryen/blob/main/src/tools/wasm-as.cpp) uses two classes "[SExpressionParser](https://github.com/WebAssembly/binaryen/blob/main/src/wasm-s-parser.h#L95)" and "[SExpressionWasmBuilder](https://github.com/WebAssembly/binaryen/blob/main/src/wasm-s-parser.h#L118)" to generate wasm from the text format.

In the "SExpressionWasmBuilder" there is a [makeExpression()](https://github.com/WebAssembly/binaryen/blob/main/src/wasm/wasm-s-parser.cpp#L1292) function which uses the [gen-s-parser.inc](https://github.com/WebAssembly/binaryen/blob/3549e3040340c706349b1ee9ab3e994279805afc/src/gen-s-parser.inc) file to match the expression in text to a function.

It has set of switch cases which compares text in the input wat file with the inbuilt functions but I could not find a function relevant to the goto expression. Since there were not any specific function I checked the implementation of the  "br" instruction whether it is possible to implement a goto with it.

The "br" instruction is implemented in the binaryen such that the branch label argument to the "br" should point to a branch which has been met by the parser and has not finished executing yet.

So there is no separate instruction to implement the goto in the Binaryen text format as well as it is not possible to implement goto with a br instruction in binaryen.

**Comment by manuranga** [comment]
Looks like going via the text format is a no-go for now.
https://github.com/WebAssembly/binaryen/discussions/4419
But the C POC you did here will be useful.
