### ISSUE TITLE
Extend the test runner to `wback`

### ISSUE THREAD

**Issue by manuranga** [poorna2152/nballerina#10]
Current test runner in `nballerina/test` dir compiles and run `ll` files. Extend this to run `wat` files.

**Comment by poorna2152** [comment]
- `wasm-interp` tool when run with the command `$ wasm-interp test.wasm --run-all-exports --trace` did not produce an output and needed a .wasm file to run the tool. So in order to run the tests the .wat files should be converted to .wasm format first and then run through the wasm-interp tool.

- The tool [wasmer](https://docs.wasmer.io/ecosystem/wasmer/getting-started) provides a tool which can take a .wat as the input and runs it without the explicit need to convert to wasm format. 
 `wasmer main.wat -i add 10 5`

- Wasmer can also generate a [.exe](https://docs.wasmer.io/ecosystem/wasmer/usage#wasmer-create-exe) file for the .wat file.

- However it doesn't seem like they provide a command line flag to import functions. Importing function can be done like [this](https://docs.wasmer.io/integrations/examples/imports-and-exports). Either through a python, C/C++, Rust or Go script.

**Comment by manuranga** [comment]
Wasmer looks like a good choice to me, please also evaluate other options. Can we use V8?

**Comment by poorna2152** [comment]
Updated the makefiles to include following commands.
- `make testwat`: run `wasm` tests
- `make testll`: run `ll` tests
- `make test`: run both `wasm` and `ll` tests.
- `make -j2 test`: run both `wasm` and `ll` tests parallely.

`wasm-opt` tool is used to convert wat to wasm. 
To find the path to the `wasm-opt` created a [shell script](https://github.com/poorna2152/nballerina/blob/scf/test/findBinaryen.sh) which search the `$HOME` directory for a wasm-opt tool.
Updated the Github action files to, 
- Download and extract the Binaryen tool releases 
- Download and install NodeJs.
